---
- name: Create Nginx dir
  file:
    path: "{{ nginx_dir }}"
    mode: "0755"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    state: directory

- name: Create Nginx .env file
  template:
    src: .env.j2
    dest: "{{ nginx_dir }}/.env"
    mode: "0660"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  notify: "Restart Nginx"

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: "{{ nginx_dir }}/docker-compose.yml"
    mode: "0644"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  notify: "Restart Nginx"
