version: '3'
services:
  proxy:
    image: nginx:1.19.2-alpine
    restart: unless-stopped
    volumes:
      - "${NGINX_CONFIG_DIR}:/etc/nginx/conf.d"
    ports:
      - "${NGINX_HTTP_BIND_ADDRESS}:${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_BIND_ADDRESS}:${NGINX_HTTPS_PORT}:443"
